from django.conf.urls import patterns, url
from django.contrib.auth.views import login as login
from annotateapp import views

urlpatterns = [
	url(r'^show_list_of_current_wordcandidates/', views.show_list_of_current_wordcandidates,name="show_list_of_current_wordcandidates"),
	url(r'^count_current_wordcandidates/', views.count_current_wordcandidates,name="count_current_wordcandidates"),
	url(r'^count_current_trials/', views.count_current_trials,name="count_current_trials"),
	url(r'^offer_trial_evaluate/', views.offer_trial_evaluate,name="offer_trial_evaluate"),
	url(r'^offer_trial_retrim/', views.offer_trial_retrim,name="offer_trial_retrim"),
	url(r'^offer_trial_errors/', views.offer_trial_errors,name="offer_trial_errors"),
	url(r'^offer_trial_ortho/', views.offer_trial_ortho,name="offer_trial_ortho"),
	url(r'^check_trial_targets/', views.check_trial_targets,name="check_trial_targets"),
	url(r'^offer_trial_retrim_list/', views.offer_trial_retrim_list,name="offer_trial_retrim_list"),
	url(r'^prepare_resources/', views.prepare_resources,name="prepare_resources"),
	url(r'^calculate_current_and_rating/', views.calculate_current_and_rating,name="calculate_current_and_rating"),
	url(r'^preload_evaluate/', views.preload_evaluate,name="preload_evaluate"),
	url(r'^evaluate/', views.evaluate,name="evaluate"),
	url(r'^offer_picture/', views.offer_picture,name="offer_picture"),
	url(r'^evaluate_practice/', views.evaluate_practice,name="evaluate_practice"),
	url(r'^preload_retrim/', views.preload_retrim,name="preload_retrim"),
	url(r'^preload_errors/', views.preload_retrim,name="preload_errors"),
	url(r'^upload_trials/', views.upload_trials,name="upload_trials"),
	url(r'^make_chunk_audios_for_new_chunks/', views.make_chunk_audios_for_new_chunks,name="make_chunk_audios_for_new_chunks"),
	url(r'^process_network_trials/', views.process_network_trials,name="process_network_trials"),
	url(r'^retrim/', views.retrim,name="retrim"),
	url(r'^retrim_list/', views.retrim_list,name="retrim_list"),
	url(r'^retrim_practice/', views.retrim_practice,name="retrim_practice"),
	url(r'^errors/', views.errors,name="errors"),
	url(r'^ortho/', views.ortho,name="ortho"),
	url(r'^accept_result_ortho/', views.accept_result_ortho,name="accept_result_ortho"),
	url(r'^accept_result_evaluate/', views.accept_result_evaluate,name="accept_result_evaluate"),
	url(r'^accept_result_retrim/', views.accept_result_retrim,name="accept_result_retrim"),
	url(r'^accept_result_errors/', views.accept_result_errors,name="accept_result_errors"),
	url(r'^accept_result_retrim_list/', views.accept_result_retrim_list,name="accept_result_retrim_list"),
	url(r'^undo_last_30_seconds/', views.undo_last_30_seconds,name="undo_last_30_seconds"),
	url(r'^textgrid/(?P<trial_id>\d{0,50})/$', views.make_trial_textgrid,),
	url(r'^retrim_copy/', views.retrim_copy,name="retrim_copy"),
	url(r'^make_hesitations/', views.make_hesitations,name="make_hesitations"),
	url(r'^correct_superbad_bug/', views.correct_superbad_bug,name="correct_superbad_bug"),
	url(r'', views.evaluate_homepage, name="evaluate_homepage"),
]